log: info
ethereum:
  chain:
    endpoint: "ETHEREUM NETWORK ENDPOINT"
    gas_limit: 3000000
    gas_price: 10000
  signer:
    private_key: "ETHEREUM ACCOUNT PRIVATE KEY"
odin:
  chain:
    endpoint: "ODIN NETWORK ENDPOINT"
    chain_id: "ODIN"
    denom: "odin"
    memo: ""
    gas_price: 10
    gas_limit: 500000
  signer:
    mnemonic: "MNEMONIC"
    password: ""
  bridge_address_storage: "ADDRESS_STORAGE.txt"
deploy:
  refund_fee: 30000000000 # 3000000 [gas_limit] * 10000 [gas_price]
  locking_funds_allowed: true
  claiming_locked_funds_allowed: false
  supported_tokens:
    - "SUPPORTED TOKEN ADDRESS"
    - "ANOTHER ONE SUPPORTED TOKEN ADDRESS"
