log: info
ethereum:
  chain:
    endpoint: "ETHEREUM NETWORK ENDPOINT"
    gas_limit: 4000000
    gas_price: 10000000000
  signer:
    private_key: "ETHEREUM ACCOUNT PRIVATE KEY"
odin:
  chain:
    endpoint: "ODIN NETWORK ENDPOINT"
    chain_id: "ODIN"
    denom: "odin"
    memo: ""
    gas_price: 10
    gas_limit: 500000
  signer:
    mnemonic: "MNEMONIC"
    password: ""
    derivation: "m/44'/494'/0'/0/0"
  bridge_address_storage: "ADDRESS_STORAGE.txt"
deploy:
  refund_gas_limit: 1000000
  depositing_allowed: true
  locking_funds_allowed: true
  claiming_locked_funds_allowed: false
  supported_tokens:
    - "SUPPORTED TOKEN ADDRESS"
    - "ANOTHER ONE SUPPORTED TOKEN ADDRESS"
fix:
  client_endpoint: "tcp://<ODIN NETWORK IP>:26657"
  from_block_number: 10277868
  bridge_address: "BRIDGE ADDRESS"
  max_txs_per_page: 100