log: info
ethereum:
  endpoint: "ETHEREUM NETWORK ENDPOINT"
odin:
  endpoint: "ODIN NETWORK ENDPOINT"
  storage: "ADDRESS_STORAGE.txt"
deployer:
  private_key: "ETHEREUM ACCOUNT PRIVATE KEY"
  gas_limit: "1200000"
